Add docker
baston7/java-shareit pull request #4
Opened 2022-12-04 18:25 UTC by baston7

2022-12-06 11:45 UTC, AnastasiyaFomkina requested changes
Отличная работа - молодец 👍

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on gateway/Dockerfile
> +FROM amazoncorretto:11-alpine-jdk
👍

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/exeption/ErrorHandler.java
> +    public ErrorResponse handleIllegalArgumentException(final IllegalArgumentException e) {
Нужно переименовать однобуквенный параметр. В коммерческой разработке принято называть переменные "осмысленно", так код проще читать

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on docker-compose.yml
> +version: '3.8'
👍

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +import org.springframework.http.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    List<ItemDto> items;
Не хватает модификатора доступа

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
Добавь, пожалуйста, модификаторы доступа к полям

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long requestId;
И в этом классе тоже

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    String email;
Нужно добавить модификаторы доступа полям

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> -public class BookingControllerTests {
Нужно вернуть тесты, это важная часть проекта, которая помогает отлавливать баги и мониторить работоспособность новых бизнес-функций

2022-12-06 11:45 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        State state1 = State.valueOf(state);
Лучше переименовать переменную `state1` во что-то более "осмысленное".  Цифры в названиях переменных считаются "code-smell"  и делают код менее читаемым

2022-12-06 19:00 UTC, baston7 commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +import org.springframework.http.*;
спасибо, не знал

2022-12-06 19:04 UTC, baston7 commented on server/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
Там стоит аннотация @FieldDefaults(level = AccessLevel.PRIVATE). Сделал везде одинаково и вернул модификаторы

2022-12-06 19:04 UTC, baston7 commented on server/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long requestId;
Там стоит аннотация @FieldDefaults(level = AccessLevel.PRIVATE). Сделал везде одинаково и вернул модификаторы

2022-12-06 19:04 UTC, baston7 commented on server/src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    String email;
Там стоит аннотация @FieldDefaults(level = AccessLevel.PRIVATE). Сделал везде одинаково и вернул модификаторы

2022-12-06 21:20 UTC, baston7 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> -public class BookingControllerTests {
вернул тесты+ добавил на валидацию в новых  контроллерах

2022-12-07 12:41 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
Прости, не заметила аннотацию :)

2022-12-07 12:50 UTC, AnastasiyaFomkina approved these changes

2022-12-07 12:51 UTC, AnastasiyaFomkina commented on server/src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    LocalDateTime created;
Можно было и ее оставить, это непринципиально, главное, что есть модификаторы 👍

2022-12-07 18:41 UTC, merged